version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: America/Chicago
    open-pull-requests-limit: 10
    groups:
      non-breaking:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "09:30"
      timezone: America/Chicago
    open-pull-requests-limit: 10
    groups:
      non-breaking:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      security:
        applies-to: security-updates
        patterns:
          - "*"
